package com.example.topratedservice.grpc;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gRPC.proto

public final class GRPC {
  private GRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TopRatedRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TopRatedRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code TopRatedRequest}
   */
  public static final class TopRatedRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TopRatedRequest)
      TopRatedRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopRatedRequest.newBuilder() to construct.
    private TopRatedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopRatedRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TopRatedRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPC.internal_static_TopRatedRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPC.internal_static_TopRatedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPC.TopRatedRequest.class, GRPC.TopRatedRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPC.TopRatedRequest)) {
        return super.equals(obj);
      }
      GRPC.TopRatedRequest other = (GRPC.TopRatedRequest) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPC.TopRatedRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPC.TopRatedRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPC.TopRatedRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPC.TopRatedRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPC.TopRatedRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPC.TopRatedRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPC.TopRatedRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPC.TopRatedRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPC.TopRatedRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPC.TopRatedRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPC.TopRatedRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPC.TopRatedRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPC.TopRatedRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TopRatedRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TopRatedRequest)
        GRPC.TopRatedRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPC.internal_static_TopRatedRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPC.internal_static_TopRatedRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPC.TopRatedRequest.class, GRPC.TopRatedRequest.Builder.class);
      }

      // Construct using GRPC.TopRatedRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPC.internal_static_TopRatedRequest_descriptor;
      }

      @java.lang.Override
      public GRPC.TopRatedRequest getDefaultInstanceForType() {
        return GRPC.TopRatedRequest.getDefaultInstance();
      }

      @java.lang.Override
      public GRPC.TopRatedRequest build() {
        GRPC.TopRatedRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPC.TopRatedRequest buildPartial() {
        GRPC.TopRatedRequest result = new GRPC.TopRatedRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPC.TopRatedRequest) {
          return mergeFrom((GRPC.TopRatedRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPC.TopRatedRequest other) {
        if (other == GRPC.TopRatedRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TopRatedRequest)
    }

    // @@protoc_insertion_point(class_scope:TopRatedRequest)
    private static final GRPC.TopRatedRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPC.TopRatedRequest();
    }

    public static GRPC.TopRatedRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopRatedRequest>
        PARSER = new com.google.protobuf.AbstractParser<TopRatedRequest>() {
      @java.lang.Override
      public TopRatedRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TopRatedRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopRatedRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPC.TopRatedRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TopRatedResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TopRatedResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    java.util.List<GRPC.Movie> 
        getMovieList();
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    GRPC.Movie getMovie(int index);
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    int getMovieCount();
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    java.util.List<? extends GRPC.MovieOrBuilder> 
        getMovieOrBuilderList();
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    GRPC.MovieOrBuilder getMovieOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code TopRatedResponse}
   */
  public static final class TopRatedResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TopRatedResponse)
      TopRatedResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TopRatedResponse.newBuilder() to construct.
    private TopRatedResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TopRatedResponse() {
      movie_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TopRatedResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPC.internal_static_TopRatedResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPC.internal_static_TopRatedResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPC.TopRatedResponse.class, GRPC.TopRatedResponse.Builder.class);
    }

    public static final int MOVIE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<GRPC.Movie> movie_;
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @java.lang.Override
    public java.util.List<GRPC.Movie> getMovieList() {
      return movie_;
    }
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends GRPC.MovieOrBuilder> 
        getMovieOrBuilderList() {
      return movie_;
    }
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @java.lang.Override
    public int getMovieCount() {
      return movie_.size();
    }
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @java.lang.Override
    public GRPC.Movie getMovie(int index) {
      return movie_.get(index);
    }
    /**
     * <code>repeated .Movie movie = 1;</code>
     */
    @java.lang.Override
    public GRPC.MovieOrBuilder getMovieOrBuilder(
        int index) {
      return movie_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < movie_.size(); i++) {
        output.writeMessage(1, movie_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < movie_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, movie_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPC.TopRatedResponse)) {
        return super.equals(obj);
      }
      GRPC.TopRatedResponse other = (GRPC.TopRatedResponse) obj;

      if (!getMovieList()
          .equals(other.getMovieList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMovieCount() > 0) {
        hash = (37 * hash) + MOVIE_FIELD_NUMBER;
        hash = (53 * hash) + getMovieList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPC.TopRatedResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPC.TopRatedResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPC.TopRatedResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPC.TopRatedResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPC.TopRatedResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPC.TopRatedResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPC.TopRatedResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPC.TopRatedResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPC.TopRatedResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPC.TopRatedResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPC.TopRatedResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPC.TopRatedResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPC.TopRatedResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TopRatedResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TopRatedResponse)
        GRPC.TopRatedResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPC.internal_static_TopRatedResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPC.internal_static_TopRatedResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPC.TopRatedResponse.class, GRPC.TopRatedResponse.Builder.class);
      }

      // Construct using GRPC.TopRatedResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (movieBuilder_ == null) {
          movie_ = java.util.Collections.emptyList();
        } else {
          movie_ = null;
          movieBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPC.internal_static_TopRatedResponse_descriptor;
      }

      @java.lang.Override
      public GRPC.TopRatedResponse getDefaultInstanceForType() {
        return GRPC.TopRatedResponse.getDefaultInstance();
      }

      @java.lang.Override
      public GRPC.TopRatedResponse build() {
        GRPC.TopRatedResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPC.TopRatedResponse buildPartial() {
        GRPC.TopRatedResponse result = new GRPC.TopRatedResponse(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(GRPC.TopRatedResponse result) {
        if (movieBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            movie_ = java.util.Collections.unmodifiableList(movie_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.movie_ = movie_;
        } else {
          result.movie_ = movieBuilder_.build();
        }
      }

      private void buildPartial0(GRPC.TopRatedResponse result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPC.TopRatedResponse) {
          return mergeFrom((GRPC.TopRatedResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPC.TopRatedResponse other) {
        if (other == GRPC.TopRatedResponse.getDefaultInstance()) return this;
        if (movieBuilder_ == null) {
          if (!other.movie_.isEmpty()) {
            if (movie_.isEmpty()) {
              movie_ = other.movie_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMovieIsMutable();
              movie_.addAll(other.movie_);
            }
            onChanged();
          }
        } else {
          if (!other.movie_.isEmpty()) {
            if (movieBuilder_.isEmpty()) {
              movieBuilder_.dispose();
              movieBuilder_ = null;
              movie_ = other.movie_;
              bitField0_ = (bitField0_ & ~0x00000001);
              movieBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMovieFieldBuilder() : null;
            } else {
              movieBuilder_.addAllMessages(other.movie_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                GRPC.Movie m =
                    input.readMessage(
                        GRPC.Movie.parser(),
                        extensionRegistry);
                if (movieBuilder_ == null) {
                  ensureMovieIsMutable();
                  movie_.add(m);
                } else {
                  movieBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<GRPC.Movie> movie_ =
        java.util.Collections.emptyList();
      private void ensureMovieIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          movie_ = new java.util.ArrayList<GRPC.Movie>(movie_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPC.Movie, GRPC.Movie.Builder, GRPC.MovieOrBuilder> movieBuilder_;

      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public java.util.List<GRPC.Movie> getMovieList() {
        if (movieBuilder_ == null) {
          return java.util.Collections.unmodifiableList(movie_);
        } else {
          return movieBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public int getMovieCount() {
        if (movieBuilder_ == null) {
          return movie_.size();
        } else {
          return movieBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public GRPC.Movie getMovie(int index) {
        if (movieBuilder_ == null) {
          return movie_.get(index);
        } else {
          return movieBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder setMovie(
          int index, GRPC.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.set(index, value);
          onChanged();
        } else {
          movieBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder setMovie(
          int index, GRPC.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.set(index, builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addMovie(GRPC.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.add(value);
          onChanged();
        } else {
          movieBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addMovie(
          int index, GRPC.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.add(index, value);
          onChanged();
        } else {
          movieBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addMovie(
          GRPC.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.add(builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addMovie(
          int index, GRPC.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.add(index, builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder addAllMovie(
          java.lang.Iterable<? extends GRPC.Movie> values) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, movie_);
          onChanged();
        } else {
          movieBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder clearMovie() {
        if (movieBuilder_ == null) {
          movie_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          movieBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public Builder removeMovie(int index) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.remove(index);
          onChanged();
        } else {
          movieBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public GRPC.Movie.Builder getMovieBuilder(
          int index) {
        return getMovieFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public GRPC.MovieOrBuilder getMovieOrBuilder(
          int index) {
        if (movieBuilder_ == null) {
          return movie_.get(index);  } else {
          return movieBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public java.util.List<? extends GRPC.MovieOrBuilder> 
           getMovieOrBuilderList() {
        if (movieBuilder_ != null) {
          return movieBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(movie_);
        }
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public GRPC.Movie.Builder addMovieBuilder() {
        return getMovieFieldBuilder().addBuilder(
            GRPC.Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public GRPC.Movie.Builder addMovieBuilder(
          int index) {
        return getMovieFieldBuilder().addBuilder(
            index, GRPC.Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .Movie movie = 1;</code>
       */
      public java.util.List<GRPC.Movie.Builder> 
           getMovieBuilderList() {
        return getMovieFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          GRPC.Movie, GRPC.Movie.Builder, GRPC.MovieOrBuilder> 
          getMovieFieldBuilder() {
        if (movieBuilder_ == null) {
          movieBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              GRPC.Movie, GRPC.Movie.Builder, GRPC.MovieOrBuilder>(
                  movie_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          movie_ = null;
        }
        return movieBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TopRatedResponse)
    }

    // @@protoc_insertion_point(class_scope:TopRatedResponse)
    private static final GRPC.TopRatedResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPC.TopRatedResponse();
    }

    public static GRPC.TopRatedResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TopRatedResponse>
        PARSER = new com.google.protobuf.AbstractParser<TopRatedResponse>() {
      @java.lang.Override
      public TopRatedResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TopRatedResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TopRatedResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPC.TopRatedResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Movie)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string movieId = 1;</code>
     * @return The movieId.
     */
    java.lang.String getMovieId();
    /**
     * <code>string movieId = 1;</code>
     * @return The bytes for movieId.
     */
    com.google.protobuf.ByteString
        getMovieIdBytes();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string overview = 3;</code>
     * @return The overview.
     */
    java.lang.String getOverview();
    /**
     * <code>string overview = 3;</code>
     * @return The bytes for overview.
     */
    com.google.protobuf.ByteString
        getOverviewBytes();
  }
  /**
   * Protobuf type {@code Movie}
   */
  public static final class Movie extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Movie)
      MovieOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Movie.newBuilder() to construct.
    private Movie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Movie() {
      movieId_ = "";
      title_ = "";
      overview_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Movie();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GRPC.internal_static_Movie_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GRPC.internal_static_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GRPC.Movie.class, GRPC.Movie.Builder.class);
    }

    public static final int MOVIEID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object movieId_ = "";
    /**
     * <code>string movieId = 1;</code>
     * @return The movieId.
     */
    @java.lang.Override
    public java.lang.String getMovieId() {
      java.lang.Object ref = movieId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        movieId_ = s;
        return s;
      }
    }
    /**
     * <code>string movieId = 1;</code>
     * @return The bytes for movieId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMovieIdBytes() {
      java.lang.Object ref = movieId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        movieId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OVERVIEW_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object overview_ = "";
    /**
     * <code>string overview = 3;</code>
     * @return The overview.
     */
    @java.lang.Override
    public java.lang.String getOverview() {
      java.lang.Object ref = overview_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        overview_ = s;
        return s;
      }
    }
    /**
     * <code>string overview = 3;</code>
     * @return The bytes for overview.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOverviewBytes() {
      java.lang.Object ref = overview_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        overview_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(movieId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, movieId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(overview_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, overview_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(movieId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, movieId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(overview_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, overview_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof GRPC.Movie)) {
        return super.equals(obj);
      }
      GRPC.Movie other = (GRPC.Movie) obj;

      if (!getMovieId()
          .equals(other.getMovieId())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getOverview()
          .equals(other.getOverview())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
      hash = (53 * hash) + getMovieId().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + OVERVIEW_FIELD_NUMBER;
      hash = (53 * hash) + getOverview().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static GRPC.Movie parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPC.Movie parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPC.Movie parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPC.Movie parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPC.Movie parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GRPC.Movie parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GRPC.Movie parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPC.Movie parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPC.Movie parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static GRPC.Movie parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static GRPC.Movie parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static GRPC.Movie parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(GRPC.Movie prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Movie}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Movie)
        GRPC.MovieOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GRPC.internal_static_Movie_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GRPC.internal_static_Movie_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GRPC.Movie.class, GRPC.Movie.Builder.class);
      }

      // Construct using GRPC.Movie.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        movieId_ = "";
        title_ = "";
        overview_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GRPC.internal_static_Movie_descriptor;
      }

      @java.lang.Override
      public GRPC.Movie getDefaultInstanceForType() {
        return GRPC.Movie.getDefaultInstance();
      }

      @java.lang.Override
      public GRPC.Movie build() {
        GRPC.Movie result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public GRPC.Movie buildPartial() {
        GRPC.Movie result = new GRPC.Movie(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(GRPC.Movie result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.movieId_ = movieId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.title_ = title_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.overview_ = overview_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GRPC.Movie) {
          return mergeFrom((GRPC.Movie)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GRPC.Movie other) {
        if (other == GRPC.Movie.getDefaultInstance()) return this;
        if (!other.getMovieId().isEmpty()) {
          movieId_ = other.movieId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getOverview().isEmpty()) {
          overview_ = other.overview_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                movieId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                overview_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object movieId_ = "";
      /**
       * <code>string movieId = 1;</code>
       * @return The movieId.
       */
      public java.lang.String getMovieId() {
        java.lang.Object ref = movieId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          movieId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       * @return The bytes for movieId.
       */
      public com.google.protobuf.ByteString
          getMovieIdBytes() {
        java.lang.Object ref = movieId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          movieId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string movieId = 1;</code>
       * @param value The movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        movieId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMovieId() {
        movieId_ = getDefaultInstance().getMovieId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string movieId = 1;</code>
       * @param value The bytes for movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        movieId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object overview_ = "";
      /**
       * <code>string overview = 3;</code>
       * @return The overview.
       */
      public java.lang.String getOverview() {
        java.lang.Object ref = overview_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          overview_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string overview = 3;</code>
       * @return The bytes for overview.
       */
      public com.google.protobuf.ByteString
          getOverviewBytes() {
        java.lang.Object ref = overview_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          overview_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string overview = 3;</code>
       * @param value The overview to set.
       * @return This builder for chaining.
       */
      public Builder setOverview(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        overview_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string overview = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOverview() {
        overview_ = getDefaultInstance().getOverview();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string overview = 3;</code>
       * @param value The bytes for overview to set.
       * @return This builder for chaining.
       */
      public Builder setOverviewBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        overview_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Movie)
    }

    // @@protoc_insertion_point(class_scope:Movie)
    private static final GRPC.Movie DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new GRPC.Movie();
    }

    public static GRPC.Movie getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Movie>
        PARSER = new com.google.protobuf.AbstractParser<Movie>() {
      @java.lang.Override
      public Movie parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Movie> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Movie> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public GRPC.Movie getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopRatedRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopRatedRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TopRatedResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TopRatedResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Movie_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Movie_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngRPC.proto\"\021\n\017TopRatedRequest\")\n\020TopRa" +
      "tedResponse\022\025\n\005movie\030\001 \003(\0132\006.Movie\"9\n\005Mo" +
      "vie\022\017\n\007movieId\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\020\n\010o" +
      "verview\030\003 \001(\t2M\n\017TopRatedService\022:\n\021GetT" +
      "opRatedMovies\022\020.TopRatedRequest\032\021.TopRat" +
      "edResponse\"\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TopRatedRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TopRatedRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopRatedRequest_descriptor,
        new java.lang.String[] { });
    internal_static_TopRatedResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TopRatedResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TopRatedResponse_descriptor,
        new java.lang.String[] { "Movie", });
    internal_static_Movie_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Movie_descriptor,
        new java.lang.String[] { "MovieId", "Title", "Overview", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
